### ISSUE TITLE
Using for ethos upgrade?

### ISSUE THREAD

**Issue by stone212** [cynixx3/ethOS-controller#3]
Not a bug but a question, is it considered safe to use this for upgrading ethos like:

`./ec -cs udo ethos-update && sleep 5 && sudo reboot`

**Comment by stone212** [comment]
(After first rebooting all rigs)

**Comment by cynixx3** [comment]
Most of the bash special characters need escaping. & > < | \ each need a \ IE:
`./ec -qc 'if [ "$(cat /opt/ethos/etc/version)" != "1.3.3" ]; then sudo reboot ; fi'`
`./ec -qc 'if [ "$(cat /opt/ethos/etc/version)" != "1.3.3" ]; then sudo ethos-update \&\& sleep 5 \&\& sudo reboot ; fi'`

**Comment by stone212** [comment]
Yes it was the same mistake I made in the other thread.  I wasn't thinking very well.  Thank you.
